sudo: required
dist: bionic
language: c

cache:
    apt: true

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install git libboost-all-dev gcc g++ python make automake m4 libtool aptitude -y
  - sudo aptitude install libc6-dev-i386 gcc-multilib -y

before_script:
  - git submodule update --init
  - git submodule foreach git pull origin master

script:
  - ./scripts/setup.sh --riot 1 --contiki-ng 1
  - timeout 600 ./regression/regress.sh regression/full.set
