name: Setup & Regress

on:
  push:
    branches: [ ot-integration ]
  pull_request:
    branches: [ ot-integration ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: ./scripts/setup.sh
    # Disabled for now, as the following tests fail: TC_two_contiki_nodes.test, TC_two_mixed_nodes.test, TC_basic_plc.test
    #- name: Regression
    #  run: timeout 600 ./regression/regress.sh regression/full.set
    
